# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: TimeKpr-nExT
version: "0.0.16"
slug: timekpr
description: Allows remote control of timekpr instances via web-ui
url: "https://github.com/ezméghiányzik"
timezone: true
arch:
  - aarch64
  - amd64
init: false
ingress: true
ingress_port: 5001
map:
  - share:rw
  - data:rw
options:
  ssh_private_key :
panel_icon: mdi:clock-in
panel_title: timekpr
#ports:
#  22/tcp: null
#  5001/tcp: 5001
schema:
  ssh_private_key: str
